version: '3.8'

services:
  backend:
    build: backend/.
    image: fern018/backend:latest
    ports:
      - "3000:3000"
    restart: always
    networks:
      - ELnetwork

  frontend:
    build: frontend/.
    image: fern018/frontend:latest
    ports:
      - "8080:8080"
    networks:
      - ELnetwork

networks:
  ELnetwork:
    driver: bridge  