version: '3.8'

services:
  backend:
    build: backEnd/.
    image: fern018/backend:latest
    ports:
      - "3000:3000"
    restart: always
    networks:
      - ELnetwork

  frontend:
    build: frontEnd/.
    image: fern018/frontend:latest
    ports:
      - "8081:8081"
    networks:
      - ELnetwork

networks:
  ELnetwork:
    driver: bridge  