version: '3.8'

services:
  backend:
    build: backend/.
    image: fern018/backend:latest
    ports:
      - "3001:3001"
    restart: always
    networks:
      - ELnetwork

  frontend:
    build: frontend/.
    image: fern018/frontend:latest
    ports:
      - "5173:5173"
    networks:
      - ELnetwork

networks:
  ELnetwork:
    driver: bridge  
